// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Hug_Bears

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_heart8bit = NULL;
// event funtions
void ui_event_heart8bit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Lub_Animation(ui_heart8bit, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Dub_Animation(ui_heart8bit, 0);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heart8bit = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_heart8bit, &ui_img_2076927008);
    lv_obj_set_width(ui_heart8bit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heart8bit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_heart8bit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heart8bit, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heart8bit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_heart8bit, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_heart8bit, ui_event_heart8bit, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_heart8bit = NULL;

}
