// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Hug_Bears

#ifndef _HUG_BEARS_UI_H
#define _HUG_BEARS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Lub_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Dub_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * dub_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * return_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * rest_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_2076927008);    // assets/8_bit_heart_icon-no background.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
